namespace ProblemsSolver.Problems
{
    // Problem description:
    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    public class Problem2 : IProblem<int>
    {
        int prev = 0;     //Previous even member sequence of Fibonacci
        int current = 2;  //Current even member sequence of Fibonacci
        int sum = 0;

        public int GetResult()
        {
            return sum;
        }

        public void Solution()
        {
            while(current < 4000000)
            {
                sum += current;
                current = current * 4 + prev;
                prev = (current - prev)/4 ;
            }
        }
        
    }
}
